### ISSUE TITLE
length on empty arrays is enumerable

### ISSUE THREAD

**Issue by AlmirKadric** [Wizcorp/node-tomes#43]
The length property on arrays should not be enumerable. However when we have an empty array it is for some reason.

```
var Tome = require('tomes').Tome;
var test = Tome.conjure([]);
for (var i in test) {
  if (test.hasOwnProperty(i)) {
    console.log(i);
  }
}
VM4171:6 length
undefined
```

**Comment by bjornstar** [comment]
I tried it in node and didn't see the problem, but had problems with _events being enumerable. Definitely saw it in Chrome. My advice is to not use for in to iterate over arrays.

**Comment by ronkorving** [comment]
We could try to replace it with a getter that returns _arr.length and see if that fixes the behavior. That would also remove the need for length updates left and right. But in essence, length is a non-enumerable. I wonder what affects that.

@AlmirKadric Once length is 0 and it shows up, when you push something to the array again, does it start to behave again or is it broken forever on the tome once length has become 0?

**Comment by ronkorving** [comment]
I see `length` too on a unit test I just wrote. Since #53 though, EventEmitter's properties created during construction also show up. Arrrrg...

**Comment by ronkorving** [comment]
Solution may follow in #54
